### ISSUE TITLE
Meshing of `example_4` fails

### ISSUE THREAD

**Issue by krzysztofarendt** [krzysztofarendt/building3d#29]
```
Traceback (most recent call last):
  File "/home/krza/code/building3d/examples/example_4.py", line 79, in <module>
    building.generate_simulation_mesh(include_volumes=True)
  File "/home/krza/code/building3d/building3d/geom/building.py", line 119, in generate_simulation_mesh
    self.mesh.generate(solidmesh=include_volumes)
  File "/home/krza/code/building3d/building3d/mesh/mesh.py", line 76, in generate
    self.solidmesh.generate(boundary_vertices)
  File "/home/krza/code/building3d/building3d/mesh/solidmesh.py", line 87, in generate
    vertices, elements = delaunay_tetrahedralization(
  File "/home/krza/code/building3d/building3d/mesh/tetrahedralization.py", line 346, in delaunay_tetrahedrali
zation
    assert set(np.unique(count_interior)) == set([0, 4]), \
AssertionError: Some interior elements have < 4 neighbors
```

**Comment by krzysztofarendt** [comment]
I don't see this error anymore.
