### ISSUE TITLE
Ray outside building (simulation with 50k rays)

### ISSUE THREAD

**Issue by krzysztofarendt** [krzysztofarendt/building3d#56]
```
Finding target surface for each ray...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:45<00:00, 474.89it/s]
Simulation...
 20%|██████████████████████████████████████████▏                                                                                                                                                                        | 50/250 [16:59<1:07:56, 20.38s/it]
Traceback (most recent call last):
  File "/home/krza/code/building3d/examples/example_6_ray_sim.py", line 48, in <module>
    raysim.simulate(250)
  File "/home/krza/code/building3d/building3d/simulators/rays/simulator.py", line 149, in simulate
    self.forward()
  File "/home/krza/code/building3d/building3d/simulators/rays/simulator.py", line 117, in forward
    self.rays[i].update_location()
  File "/home/krza/code/building3d/building3d/simulators/rays/ray.py", line 72, in update_location
    raise e
  File "/home/krza/code/building3d/building3d/simulators/rays/ray.py", line 66, in update_location
    self.location = get_location(self.position, self.building, target_solid, self.location)
  File "/home/krza/code/building3d/building3d/simulators/rays/get_location.py", line 44, in get_location
    raise RuntimeError(
RuntimeError: Point (pt(x=-0.00,y=0.07,z=0.06, id=0x7fbeb7ffb7c0)) not found in any of the solids of Building(name=building, zones=['zone'], volume=48.00, id=0x7fbef2620d30)
```

**Comment by krzysztofarendt** [comment]
It does not happen anymore.
